### ISSUE TITLE
PUR button 

### ISSUE THREAD

**Issue by ShalokShalom** [PacBSD/abs#28]
does not work from here: https://pacbsd.org/#

**Comment by vendion** [comment]
Please report website issues in [PacBSD/pacweb](https://github.com/PacBSD/pacweb) rather than here as this is for issues related to packages.

That said the reason that doesn't work is we currently are not running a User Repository service so there is nothing for  it to point to and the links just never  removed from the website, forum, and wiki.

**Comment by ShalokShalom** [comment]
If that is, how you treat all your issues, good night.
